from typing import Literal, Optional, get_args, override

from game.components.message import Message
from utils.types import ChannelId, InteractionId, MessageId, PlayerId

InteractionType = Literal[
    'send_message',
    'delete_message',
    'select_option',
    'deselect_option']
INTERACTION_TYPES = get_args(InteractionType)

class Interaction(object):
    """
    an object for storing the data generated by a players interaction with the interface
    
    each interaction follows a designated InteractionType, but it is up to the implemantation to actually store the relavant data
    """
    def __init__(
            self,
            interaction_type:InteractionType, 
            player_id:Optional[PlayerId] = None, 
            interaction_id:Optional[InteractionId] = None,
            channel_id:Optional[ChannelId] = None,
            reply_to_message_id:Optional[MessageId] = None,
            content:Optional[str] = None,
            choice_index:Optional[int] = None
            ):
        self.player_id:Optional[PlayerId] = player_id
        self.interaction_id:Optional[InteractionId] = interaction_id
        self.channel_id:Optional[ChannelId] = channel_id
        self.reply_to_message_id:Optional[MessageId] = reply_to_message_id

        self.content:Optional[str] = content
        self.interaction_type:InteractionType = interaction_type

        self.choice_index:Optional[int] = choice_index
    @override
    def __repr__(self) -> str:
        return f"Interaction[{self.interaction_type}]]({self.content})"
    def reply(self,content:str) -> Message:
        return Message(
            content = content,
            channel_id=self.channel_id,
            reply_to_id=self.interaction_id
        )
        
